platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!


#other sources
source 'https://github.com/CocoaPods/Specs.git'

target 'C4GenericFilter_Example' do
  pod 'C4GenericFilter', :path => '../'

  target 'C4GenericFilter_Tests' do
    inherit! :search_paths
    
  
  end
end
